### ISSUE TITLE
Collapse Stickies

### ISSUE THREAD

**Issue by Pamasich** [Pamasich/kbin-kes#19]
On magazines like kbinmeta@kbin.social. there's simply too many stickies. It should be possible to collapse them.

Will have to face the same issue as #11 and #18 — how to identify stickies. Either of them getting resolved should make this addon way easier to develop.

**Comment by Pamasich** [comment]
Stickies can be easily identified. Just do a GET request for all qualifying posts with the ld-json accept header, there will be a property to check if it's stickied or not.

**Comment by Pamasich** [comment]
> Maybe these two could be combined actually and a mod made which groups the stickies together and allows to collapse them.

**Comment by Pamasich** [comment]
Mistakenly set it to development.

**Comment by Pamasich** [comment]
I think that my userstyle should be enriched with a style that changes the pin icon color to green.

As for the script/mod, it should focus on what javascript excels at. I think the stickies should be grouped together, with minimal information like their titles visible. There should be two buttons, one to fully collapse them, and one to expand them, showing the full posts as they look now.

**Comment by aclist** [comment]
I made a very simple implementation of a collapse/expand stickies mod since it was dead simple to do and added it to the testing branch, take a look. It doesn't add every feature you listed here, but I think it's a good start for a basic implementation. I'm going to add your name to the authors list since we had the idea at the same time. One thing that should be added is the ability to customize the border color--currently it's hardcoded. But KES makes that easy.

**Comment by aclist** [comment]
I've just remembered from our prior conversation that using aria labels is not robust enough due to the different languages. I'll have to make a change to check for something more generic like the thumbtack icon. This should probably go into the documentation as well, as it's a common pitfall when designing against one language.

**Comment by Pamasich** [comment]
I'll close this for now since the ability to collapse stickies has been added. I do still want to try implementing a more condensed sticky list some day, but that can be its own todo item.
