### ISSUE TITLE
Fix the potential future rate limit problem before it becomes a problem

### ISSUE THREAD

**Issue by Pamasich** [Pamasich/kbin-kes#63]
Aclist has mentioned in another issue a potential future problem:

> I think eventually this is going to bump into the rate limit if the number of mods exceeds about 80 (currently at about half that). Maybe we should be thinking about keeping atomic scripts as files-of-reference in the source code and accepting atomic scripts for PRs, but having a build routine that consolidates all of them into a single JS file from which the functions can be sourced at runtime. (At this point, functions would absolutely have to be private to each mod to prevent collisions, and any mods not following this would need to be refactored. Or some sort of mod function namespacing logic could be used.) This would effectively shrink the requires from N==mods to 1, plus a handful of files like the CSS.

It's not at all a priority currently, but do consider it for the future.
It would require me to look into bash scripting (git comes with a tool to run them on windows), so there's quite some effort expected despite the relatively simple task.
So I'll let aclist handle this first and only tackle it if the number of mods goes up a lot and it becomes actually needed.

While at it, also look into whether it's possible to add some sort of prefix to top level functions and variables (to avoid having to use a namespace function or manually use unique names; to keep things simpler for mod developers). The mod's internal name could then be used as the prefix.

[Matching issue on the main repository](https://github.com/aclist/kbin-kes/issues/253)

**Comment by aclist** [comment]
Updating the build routine is fairly simple for me to do, just need to concatenate each file in the KES generation script and then audit the result for errors. Theoretically, mod developers could just do what they want (provided their mod keeps a unique name) and the build script could update the functions in-place with a namespace based on the name of the mod, essentially wrapping the entire mod script. 

I mainly think namespacing is good because the current approach, even when using private functions, is calling for mod authors to essentially create long-winded and obscure initialization function names like "fixCodeblocks_InitFunction" for the sake of being semantically unique, and then having to add this init function to the JSON manifest. It seems like it'd be better to just inherit the canonical name of the mod, and then let KES call whatever resides underneath it. We already define an optional "namespace" key in the JSON which is used for mods that need to save config settings, so maybe just lean into that and use qualified namespaces where:

- The name of the mod
- The namespace for saving settings
- The namespace for stepping through the init function

are identical, which makes things more predictable.
